export const FETCH_PRODUCTS= "FETCH_PRODUCTS"; 
export const SET_PRODUCTS= "SET_PRODUCTS";
export const SELECTED_PRODCT= "SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT= "REMOVE_SELECTED_PRODUCT";