export const imgList = [
  { id: 1, url: "/images/banner/img0.png" },
  { id: 2, url: "/images/banner/img1.jpg" },
  { id: 3, url: "/images/banner/img2.jpg" },
  { id: 4, url: "/images/banner/img3.jpg" },
  { id: 5, url: "/images/banner/img4.jpg" },
  { id: 6, url: "/images/banner/img5.jpg" },
  { id: 7, url: "/images/banner/img6.jpg" },
  { id: 8, url: "/images/banner/img7.jpg" },
  { id: 9, url: "/images/banner/img8.jpg" },
  { id: 10, url: "/images/banner/img9.jpg" },
  { id: 11, url: "/images/banner/img10.jpg" },
  { id: 12, url: "/images/banner/img11.jpg" },
  { id: 13, url: "/images/banner/img12.jpg" },
];
